In [2]:
import numpy as np
import pandas as pd

In [5]:
n1=np.array([[1,2,3],[4,5,3]])

In [6]:
n1

array([[1, 2, 3],
       [4, 5, 3]])

In [8]:
n2=np.arange(5,11).reshape(2,3)

In [9]:
n2

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [15]:
np.concatenate([n1,n2])

array([[ 1,  2,  3],
       [ 4,  5,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [16]:
np.concatenate([n1,n2],axis=1)

array([[ 1,  2,  3,  5,  6,  7],
       [ 4,  5,  3,  8,  9, 10]])

In [18]:
s1=pd.Series(np.arange(4))

In [19]:
s1

0    0
1    1
2    2
3    3
dtype: int32

In [20]:
s2=pd.Series(np.arange(4,8))

In [21]:
s2

0    4
1    5
2    6
3    7
dtype: int32

In [23]:
pd.concat([s1,s2],ignore_index=True)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
dtype: int32

In [24]:
pd.concat([s1,s2],axis=1)

0  1
0  0  4
1  1  5
2  2  6
3  3  7

In [27]:
pd.concat([s1,s2],keys=['s1','s2'])

s1  0    0
    1    1
    2    2
    3    3
s2  0    4
    1    5
    2    6
    3    7
dtype: int32

In [28]:
df1=pd.DataFrame(np.random.randn(9).reshape(3,3),columns=['A','B','C'])

In [29]:
df2=pd.DataFrame(np.random.randn(9).reshape(3,3),columns=['A','C','D'])

In [30]:
pd.concat([df1,df2])

A         B         C         D
0  1.502484 -1.042514 -1.560559       NaN
1 -0.284302 -0.557191 -0.512835       NaN
2 -0.747879  1.015898 -0.457391       NaN
0  0.023862       NaN  0.488342  0.373709
1  1.083179       NaN  0.906136 -1.100553
2  0.117846       NaN -0.081406 -1.391546

In [33]:
pd.concat([df1,df2],ignore_index=True,axis=0)

A         B         C         D
0  1.502484 -1.042514 -1.560559       NaN
1 -0.284302 -0.557191 -0.512835       NaN
2 -0.747879  1.015898 -0.457391       NaN
3  0.023862       NaN  0.488342  0.373709
4  1.083179       NaN  0.906136 -1.100553
5  0.117846       NaN -0.081406 -1.391546