In [1]:
import numpy as np

In [2]:
mylist=[1,2,3,4,5]

In [3]:
myarray=np.array(mylist)

In [4]:
myarray

array([1, 2, 3, 4, 5])

In [5]:
myarr=np.array([[1,2,3],[4,5,6]])

In [6]:
myarr

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
myarr.shape

(2, 3)

In [8]:
myarr.dtype

dtype('int32')

In [9]:
myarr.itemsize

4

In [10]:
myarr.size

6

In [11]:
myarr.shape=(3,2)

In [12]:
myarr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
myarr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
myarr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
myarr2=np.resize(myarr,(3,3))

In [16]:
myarr2

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
myarr3=np.arange(10)

In [32]:
myarr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
myarr3=np.linspace(10,20,5)

In [26]:
myarr3

array([10. , 12.5, 15. , 17.5, 20. ])

In [33]:
myarr3.shape=(2,5)

In [34]:
myarr3*myarr3

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [35]:
myarr-myarr

array([[0, 0],
       [0, 0],
       [0, 0]])

In [36]:
myarr+myarr

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [37]:
myarr/2

array([[0.5, 1. ],
       [1.5, 2. ],
       [2.5, 3. ]])

In [38]:
myarr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [39]:
myarr.sum()

21

In [40]:
np.sum(myarr)

21

In [41]:
np.sum(myarr,0)

array([ 9, 12])

In [42]:
np.sum(myarr,1)

array([ 3,  7, 11])

In [45]:
np.divide(myarr,myarr)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [46]:
np.multiply(myarr,myarr)

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [48]:
np.subtract(myarr3,myarr3)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [49]:
myarr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [51]:
myar=np.random.randn(3,2)

In [52]:
myar

array([[-1.56272132, -0.6685285 ],
       [ 0.1517422 , -0.87341166],
       [-2.02987791,  0.68919401]])

In [57]:
np.amin(myarr,1)

array([1, 3, 5])

In [58]:
np.amax(myarr,0)

array([5, 6])

In [59]:
mya=np.maximum(myar,myarr)

In [60]:
mya

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [61]:
mya=np.minimum(myar,myarr)

In [62]:
mya

array([[-1.56272132, -0.6685285 ],
       [ 0.1517422 , -0.87341166],
       [-2.02987791,  0.68919401]])

In [63]:
myarr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [64]:
myarr[1]

array([3, 4])

In [65]:
myarr[1:]

array([[3, 4],
       [5, 6]])

In [66]:
myarr[1][:]

array([3, 4])

In [67]:
myarr[1][1]

4

In [68]:
myarrr=myarr[:]

In [69]:
myarrr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [70]:
myarrr[1][1]=10

In [71]:
myarr

array([[ 1,  2],
       [ 3, 10],
       [ 5,  6]])

In [72]:
myarrr

array([[ 1,  2],
       [ 3, 10],
       [ 5,  6]])

In [73]:
mar=np.copy(myarr)

In [74]:
mar

array([[ 1,  2],
       [ 3, 10],
       [ 5,  6]])

In [75]:
mar[1][1]=4

In [76]:
mar

array([[1, 2],
       [3, 4],
       [5, 6]])

In [77]:
myarr

array([[ 1,  2],
       [ 3, 10],
       [ 5,  6]])

In [78]:
zero=np.zeros([5,5])

In [79]:
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [80]:
zero[1]

array([0., 0., 0., 0., 0.])

In [81]:
l=zero.shape[1]

In [82]:
for i in range(l):
    zero[i]=1

In [83]:
zero

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [84]:
for i in range(l):
    zero[i]=i

In [85]:
zero

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [86]:
zero[2:]=5

In [87]:
zero

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [92]:
zero[[1,2,3]]

array([[1., 1., 1., 1., 1.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [93]:
myarr

array([[ 1,  2],
       [ 3, 10],
       [ 5,  6]])

In [95]:
myarr.mean()

4.5

In [97]:
myarr.ptp()

9

In [98]:
myarr.ptp(1)

array([1, 7, 1])

In [99]:
myarr.ptp(0)

array([4, 8])

In [100]:
myarr.mean(1)

array([1.5, 6.5, 5.5])

In [101]:
myarr.mean(0)

array([3., 6.])

In [102]:
myarr.std()

2.9860788111948193

In [103]:
myarr.std(1)

array([0.5, 3.5, 0.5])

In [104]:
myarr.std(0)

array([1.63299316, 3.26598632])

In [105]:
myarr.var()

8.916666666666666

In [106]:
myarr.var(0)

array([ 2.66666667, 10.66666667])

In [107]:
myarr.var(1)

array([ 0.25, 12.25,  0.25])

In [115]:
np.dot(myarr,2)

array([[ 2,  4],
       [ 6, 20],
       [10, 12]])

In [116]:
myarr*2

array([[ 2,  4],
       [ 6, 20],
       [10, 12]])

In [120]:
np.median(myarr)

4.0

In [121]:
np.median(myarr,1)

array([1.5, 6.5, 5.5])

In [122]:
np.median(myarr,0)

array([3., 6.])

In [126]:
np.average(myarr)

4.5

In [130]:
myarr

array([[ 1,  2],
       [ 3, 10],
       [ 5,  6]])

In [131]:
myarr.T

array([[ 1,  3,  5],
       [ 2, 10,  6]])

In [133]:
np.transpose(myarr)

array([[ 1,  3,  5],
       [ 2, 10,  6]])

In [134]:
np.std(myarr)

2.9860788111948193

In [137]:
myarr.swapaxes(1,0)

array([[ 1,  3,  5],
       [ 2, 10,  6]])

In [138]:
np.sqrt(mar)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [139]:
np.exp(mar)

array([[  2.71828183,   7.3890561 ],
       [ 20.08553692,  54.59815003],
       [148.4131591 , 403.42879349]])

In [140]:
myarr

array([[ 1,  2],
       [ 3, 10],
       [ 5,  6]])

In [141]:
np.save("myarray",myarr)

In [145]:
m=np.load("myarray.npy")

In [146]:
m

array([[ 1,  2],
       [ 3, 10],
       [ 5,  6]])

In [147]:
mar

array([[1, 2],
       [3, 4],
       [5, 6]])

In [148]:
np.savez("ziparray",x=mar,y=m)

In [149]:
mm=np.load("ziparray.npz")

In [154]:
mm['x']

array([[1, 2],
       [3, 4],
       [5, 6]])

In [155]:
mm['y']

array([[ 1,  2],
       [ 3, 10],
       [ 5,  6]])

In [160]:
np.savetxt("artxt.txt",m,delimiter=',')

In [161]:
t=np.loadtxt("artxt.txt",delimiter=',')

In [162]:
t

array([[ 1.,  2.],
       [ 3., 10.],
       [ 5.,  6.]])

In [164]:
myarray=np.array(['usa','uk','russia','india','usa'])

In [165]:
np.unique(myarray)

array(['india', 'russia', 'uk', 'usa'], dtype='<U6')

In [169]:
np.in1d(['india'],myarray)

array([ True])

In [170]:
bolarr=np.array([True,False,False,True])

In [171]:
bolarr.any()

True

In [172]:
bolarr.all()

False

In [173]:
a=np.array([1,2,3,4])
b=np.array(['a','b','c','d'])

In [174]:
l=[(x if y else z) for x,y,z in zip(a,bolarr,b) ]

In [175]:
l

[1, 'b', 'c', 4]

In [182]:
ll=np.where(bolarr,a,b)

In [183]:
ll

array(['1', 'b', 'c', '4'], dtype='<U11')

In [184]:
broadcast=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [185]:
x=np.array([1,2,3])

In [186]:
broadcast+x

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [188]:
y=np.array([[1],[2],[4]])

In [189]:
broadcast+y

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [11, 12, 13]])